
#!/usr/bin/env bash

export MESOS_NATIVE_JAVA_LIBRARY=${MESOS_NATIVE_JAVA_LIBRARY:-/usr/lib/libmesos.so}
export LIBPROCESS_IP=${SPARK_LOCAL_IP:-"127.0.0.1"}
export SPARK_MASTER=${SPARK_MASTER:-local}
export MESOS_EXECUTOR_CORE=${MESOS_EXECUTOR_CORE:-0.1}
export SPARK_IMAGE=${SPARK_IMAGE}
export SPARK_LOCAL_IP=${SPARK_LOCAL_IP:-"127.0.0.1"}
export SPARK_PUBLIC_DNS=${SPARK_PUBLIC_DNS:-"127.0.0.1"}